version: '3.9'

services:
  app:
    build:
      container_name: miral-api
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.${APP_ENV}
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.${APP_ENV}
    command: celery -A app.celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
      - mongodb

volumes:
  mongodb_data:
